### ISSUE TITLE
I thought it's really a pretty good lightweight script interpreter. And I want to know what the scipt's grammar is. It's like javascript, C#, or is a mixed collection？

### ISSUE THREAD

**Issue by poludu** [scadiot/Dopascript#1]

**Comment by scadiot** [comment]
You can see what scripts can look like with the following examples: https://github.com/scadiot/Dopascript/tree/master/src/Dopascript.Test/Sources
Please note that I am not maintaining this project. If you still want to use it, I advise you to test it before.

**Comment by poludu** [comment]
Got it. Thanks!
